name: geog0111
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - nbsphinx
  - matplotlib
  - ipython
  - numpy
  - scipy
  - pip
  - pip:
#    - jupyter_contrib_nbextensions
    - urlpath
    - mkdocs
    - sphinx
    - mkdocs-jupyter
    - mknotebooks
    - mkdocs-exclude
    - mkdocs-git-revision-date-localized-plugin
    - recommonmark
    - sphinx-markdown-tables
    - sphinx-typlog-theme
    - mkdocs-rtd-dropdown
    - mkdocs-material
    - astropy
    - xlrd
    - pyephem
    - netCDF4
    - numpydoc
