name: geog0111
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - pip:
    - nbconvert
    - mkdocs
    - mkdocs-jupyter
    - mknotebooks
    - mkdocs-exclude
    - mkdocs-git-revision-date-localized-plugin
    - recommonmark
    - mkdocs-rtd-dropdown
    - mkdocs-material
