name: geog0133
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - python>=3
  - sphinx>=1.6
  - pandoc
  - nbconvert!=5.4
  - ipykernel
  - xlrd
  - numpy
  - pandas
  - nbsphinx
  - ipython
  - pip
  - scipy
  - pip:
    - nbsphinx
    - sphinx_rtd_theme
    - astropy
    - xlrd
    - pyephem
    - netCDF4
    - numpydoc
    - urlpath
