name: geog0133
channels:
  - conda-forge
  - defaults
dependencies:
  - pyephem
  - git
  - python>=3.7
  - nomkl
  - scipy
  - beautifulsoup4
  - numpy
  - netcdf4
  - matplotlib-base
  - matplotlib
  - pandas
  - ipython
  - numpydoc
  - astropy
  - pytest
  - jupyter_console
  - jupyter_contrib_nbextensions
  - pandocfilters
  - nbconvert
  - jupyterlab
  - pandoc
  - libnetcdf
  - ipykernel
  - ipympl
  - pip
  - yapf
  - autopep8
  - jupyter
  - pycodestyle
  - sphinx
  - fsspec
  - matplotlib
  - sphinx>=1.6
  - pandoc
  - xlrd
  - nbsphinx
  - scipy
  - pip:
    - sphinx_rtd_theme
    - netCDF4
    - urlpath
