name: geog0133
channels:
  - conda-forge
  - defaults
dependencies:
  - pyephem
  - git
  - python>=3.7
  - scipy
  - numpy
  - netcdf4
  - matplotlib-base
  - matplotlib
  - pandas
  - ipython
  - astropy
  - jupyter_console
  - jupyter_contrib_nbextensions
  - libnetcdf
  - ipykernel
  - ipympl
  - pip
  - autopep8
  - jupyter
  - fsspec
  - matplotlib
  - scipy
  - pip:
    - urlpath
